version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: airplane-tickets-ms-db
      POSTGRES_USER: airplane-tickets-ms
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: 
      context: ./airplane-tickets-ms
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/airplane-tickets-ms-db

  frontend:
    build: 
      context: ./airplane-tickets-fe
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: